### ISSUE TITLE
エンドポイントもたたけるようにする

### ISSUE THREAD

**Issue by ryotayamanaka** [g2glab/sandbox#2]
RDF のテキストボックスに URL が入力された場合はエンドポイントを参照？

取ってくる行数に制限をかけたいが、単純に LIMIT をつけると整合性のあるノードとエッジが取れない
このため、LIMIT するのでなく、行数が多すぎる場合にエラーを返すことしかできないか

**Comment by Mona144** [comment]
エンドポイントモードを追加しました
